version: "3"

services:
  frontend:
    build: "."
    image: "liquity.server:5678/liquity-frontend"
    ports:
      - "6789:443"
    volumes:
      - "./nginx.conf.tpl:/nginx.conf.tpl"
      - "${NGINX_SSL_CERTIFICATE:-~/certs/tls.crt}:/certs/tls.crt"
      - "${NGINX_SSL_CERTIFICATE_KEY:-~/certs/tls.key}:/certs/tls.key"
    environment:
      - "NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-liquity.server}"
      - "NGINX_SSL_CERTIFICATE=/certs/tls.crt"
      - "NGINX_SSL_CERTIFICATE_KEY=/certs/tls.key"
    command:
      [
        "/bin/bash",
        "-c",
        "envsubst < /nginx.conf.tpl > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'",
      ]
