version: "3"

services:
  frontend:
    build: "."
    image: "liquity/dev-frontend"
    ports:
      - "${LIQUITY_FRONTEND_HTTPS_PORT}:443"
    volumes:
      - "./nginx.conf.tpl:/nginx.conf.tpl"
      - "${LIQUITY_FRONTEND_TLS_CERTIFICATE}:/certs/tls.crt"
      - "${LIQUITY_FRONTEND_TLS_CERTIFICATE_KEY}:/certs/tls.key"
    environment:
      - "NGINX_SERVER_NAME=${LIQUITY_FRONTEND_SERVER_NAME}"
      - "NGINX_SSL_CERTIFICATE=/certs/tls.crt"
      - "NGINX_SSL_CERTIFICATE_KEY=/certs/tls.key"
    command:
      [
        "/bin/bash",
        "-c",
        "envsubst < /nginx.conf.tpl > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'",
      ]
    restart: "always"
